### ISSUE TITLE
Installation and usage instructions details

### ISSUE THREAD

**Issue by bwittman** [Coul33t/reduce-colours#1]
When I run the program with the suggested usage (`py ui/main_gui.py`), I get the following error:
```
Traceback (most recent call last):
  File "ui/main_gui.py", line 420, in <module>
    ui = Ui_MainWindow()
  File "ui/main_gui.py", line 34, in __init__
    with open('colours.json', 'r') as json_colours_file:
FileNotFoundError: [Errno 2] No such file or directory: 'colours.json'
```

I had to be *in* the `ui` directory and run: `py main_gui.py`

Also, I think PyQt5 should be added to the list of required libraries.  I had to install it in order to run the program.

I am using Python 3.7.0 (32-bit) on Windows 10.

**Comment by Coul33t** [comment]
Hello,
Thanks for telling me this. I was so used to use it myself that I forgot that it requires some additional steps before being able to use it. I'll do this asap!

**Comment by joshuata** [comment]
You might look into pipenv or poetry for automatic dependency management

**Comment by Coul33t** [comment]
Yes I was thinking about finally dipping into pipenv for dependencies, it would make for a great introduction.

**Comment by Coul33t** [comment]
This is now done, there is a `requirements.txt` file and a small tutorial.

**Comment by Coul33t** [comment]
This is now done in 6d145d3c1dffd24ecd92fffb4e6e920a65a0ee2a, there is a requirements.txt file and a small tutorial.
